config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'portfolio' => 'pages#portfolio'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">sanDunes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'We are ..', about_path %></li>
        <li><%= link_to 'Our Portfolio', portfolio_path %></li>
        <li><%= link_to 'Get in Touch', contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sanDunes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">

	<h2>We are sanDunes, your new neighbour!</h2>
	<p></p>
	<h4>In this huge world of internet, sanDunes is a team of developers working together to expand YOUR reach through building you a "web-home". We are currently based in Medina, but who knows maybe we'd like to move around a little bit in the future.</h4>
	<h4>Our main goal is to build you a home in this new world and design it as good as we can. The internet world have zaro homeless population, so if you want to live in this planet, you are required to be a settled citizen.</h4>
	<h4>The good news is that we are here to help! Every home in this planet, somehow, is very close to another. We are all neighbours, Yay! We are also very eager to accept you as our neighbour, "the more the merrier" as they say.</h4>
	<h4>Now, lets ride this 'spaceship' with us..</h4>
	<div class="center"><%= link_to 'Hop in', contact_path, class: "btn btn-primary btn-lg" %></div>

</div>

app/views/pages/contact.html.erb
<div class="jumbotron">

	<h2>Hello there!</h2>
	<p></p>
	<h4>We are looking forward to happily assist you!</h4>
	<h4>You can contact:</h4>
	<div class="center"><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  	Shofi Bahalwan</button></div>
  	<h4>if you'd like us to speak with you in English, or</h4>
  	<p></p>
	<div class="center"><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModalone">
  	Muhammad Sayed</button></div>
  	<h4>if you'd like to ask us in Arabic</h4>

  	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h2 class="modal-title" id="myModalLabel">Shofi Bahalwan</h2>
	        <h4>Back-End Developer</h4>
	      </div>
	      <div class="modal-body">
	        <p>phone number : </p>
	        <p class="text-center">(+966) 531-631-141</p>
	        <p>e-mail address : </p>
	        <p class="text-center">smbahalwan@gmail.com</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">Got it..</button>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="modal fade" id="myModalone" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h2 class="modal-title" id="myModalLabel">Muhammad Sayed</h2>
	        <h4>Front-End Developer</h4>
	      </div>
	      <div class="modal-body">
	        <p>phone number : </p>
	        <p class="text-center">(+966) 55-685-2837</p>
	        <p>e-mail address : </p>
	        <p class="text-center">memosyed@gmail.com</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">Got it..</button>
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1 class="text-center">sanDunes</h1>
	<p></p>
	<p></p>
	<h5 class="text-center">from MEDINA with <span class="glyphicon glyphicon-heart"></span> </h5>
</div></h5>

app/views/pages/portfolio.html.erb
<div class="jumbotron">

	<h2>Portfolio</h2>
	<p></p>
	<h4>Oops! Look like we haven't got anything to show you yet..</h4>
	<h4>Wanna be our first neighbour? <%= link_to 'Get in Touch', contact_path, class: "btn btn-primary btn-lg" %></h4>

</div>